version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    container_name: 'portainer-app'
    ports:
     - '9000:9000'
    networks:
     - local
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./data:/data

networks:
  local:
    driver: bridge
